# Generated by Django 4.2.1 on 2023-06-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('full_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
