# Generated by Django 4.2.1 on 2023-06-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
    ]
